[package]
org = "somap"
name = "mongodb_atlas_app"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.14.2"

[[dependency]]
org = "ballerina" 
name = "log"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "time"
version = "2.7.0"

[[dependency]]
org = "ballerina"
name = "uuid"
version = "1.10.0"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.15.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.9.0"

[[dependency]]
org = "ballerina"
name = "url"
version = "2.6.0"

[[dependency]]
org = "ballerina"
name = "email"
version = "2.12.0"

[[dependency]]
org = "ballerina"
name = "regex"
version = "1.3.2"

[[dependency]]
org = "ballerina"
name = "websocket"
version = "2.14.0"

[[dependency]]
org = "ballerina"
name = "lang.value"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "lang.string"
version = "0.0.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.8.0"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "5.1.0"

[[dependency]]
org = "ballerinai"
name = "observe"
version = "0.0.0"
